export interface PhonemeGuide {
  symbol: string; // The symbol code matching Azure Speech API output
  ipaSymbol: string; // Standard IPA display
  name: string; // Human readable category name
  type: "vowel" | "diphthong" | "nasal" | "plosive" | "fricative" | "other";
  voiced: boolean;
  tonguePosition:
    | "high-front"
    | "mid-front"
    | "low-front"
    | "high-back"
    | "mid-back"
    | "low-back"
    | "neutral"
    | "alveolar"
    | "velar"
    | "dental"
    | "diphthong-ey"
    | "diphthong-ay"
    | "diphthong-oy"
    | "diphthong-aw"
    | "diphthong-ow";
  mouthOpening: "closed" | "narrow" | "medium" | "wide";
  velum: "open" | "closed";
  descriptionCn: string;
  descriptionEn: string;
  tongueInstructions: string;
  lipInstructions: string;
  airflowInstructions: string;
  coachTips: string;
  guideWord: string;
  minimalPairs: { word1: string; word2: string; ipa1: string; ipa2: string; note: string }[];
  practiceWords: string[];
}

const SHORT_E_GUIDE: PhonemeGuide = {
  symbol: "ɛ",
  ipaSymbol: "ɛ",
  name: "Short Front Vowel (短前元音)",
  type: "vowel",
  voiced: true,
  tonguePosition: "mid-front",
  mouthOpening: "medium",
  velum: "closed",
  descriptionCn: "短前元音。嘴巴保持半开，舌前部抬到中位，声音短促稳定，不要向 /ɪ/ 滑动。它像 men, pen, get 里的元音。",
  descriptionEn: "A short front vowel. Keep the mouth moderately open and the front of the tongue at mid height. The sound is short and steady, without gliding toward /ɪ/.",
  tongueInstructions: "舌尖轻抵下齿，舌前部抬起但不要继续向上滑。保持一个稳定位置后快速结束。",
  lipInstructions: "双唇自然放松，口角略微展开。不要像 /eɪ/ 那样随着结尾继续收窄。",
  airflowInstructions: "软腭上升关闭鼻腔，声带震动，气流从口腔平稳送出。",
  coachTips: "如果 men 被说成 main，通常是你在结尾加了向 /ɪ/ 的滑动。练 men 时故意把元音收短、收稳；练 main 时再加上清晰滑动。",
  guideWord: "men",
  minimalPairs: [
    { word1: "men", word2: "main", ipa1: "mɛn", ipa2: "meɪn", note: "Short steady /ɛ/ vs gliding /eɪ/" },
    { word1: "pen", word2: "pain", ipa1: "pɛn", ipa2: "peɪn", note: "Stop the vowel early in 'pen'; glide upward in 'pain'" },
    { word1: "get", word2: "gate", ipa1: "gɛt", ipa2: "geɪt", note: "Keep 'get' short; let 'gate' move toward /ɪ/" },
    { word1: "let", word2: "late", ipa1: "lɛt", ipa2: "leɪt", note: "Do not let 'let' turn into a diphthong" },
  ],
  practiceWords: ["men", "pen", "get", "let", "said", "red", "bed", "ten"],
};

const RHOTIC_VOWEL_GUIDE: PhonemeGuide = {
  symbol: "ɝ",
  ipaSymbol: "ɝ",
  name: "R-colored Vowel (卷舌元音)",
  type: "vowel",
  voiced: true,
  tonguePosition: "neutral",
  mouthOpening: "narrow",
  velum: "closed",
  descriptionCn: "卷舌元音。先保持中央元音的口腔空间，再让舌身向后收，舌尖或舌面前部微微抬起但不要碰到上腭。",
  descriptionEn: "An r-colored vowel. Keep a central vowel shape, then retract the tongue body and slightly raise the tongue tip/front without touching the roof of the mouth.",
  tongueInstructions: "舌头整体向后收，舌尖悬空，不要像中文卷舌声母那样摩擦上腭。",
  lipInstructions: "双唇轻微收圆或放松，不要过度噘嘴；重点在舌头后收和口腔共鸣。",
  airflowInstructions: "软腭上升，声带震动，气流持续从口腔通过，不能出现擦音或弹舌。",
  coachTips: "girl, work, turn 这类词容易把 /ɝ/ 发成普通元音加中文式 r。保持一个连续的卷舌元音，不要拆成两个声音。",
  guideWord: "girl",
  minimalPairs: [
    { word1: "girl", word2: "go", ipa1: "gɝl", ipa2: "goʊ", note: "Keep the r-colored center in 'girl'" },
    { word1: "work", word2: "walk", ipa1: "wɝk", ipa2: "wɔk", note: "Retract the tongue for 'work'; open more for 'walk'" },
    { word1: "turn", word2: "ten", ipa1: "tɝn", ipa2: "tɛn", note: "Do not flatten 'turn' into a short front vowel" },
  ],
  practiceWords: ["girl", "work", "turn", "word", "learn", "early", "certainly", "her"],
};

export const PHONEME_GUIDES: Record<string, PhonemeGuide> = {
  // --- VOWELS & DIPHTHONGS ---
  "ɛ": SHORT_E_GUIDE,
  e: SHORT_E_GUIDE,
  eh: SHORT_E_GUIDE,
  "ɝ": RHOTIC_VOWEL_GUIDE,
  "ɚ": RHOTIC_VOWEL_GUIDE,
  er: RHOTIC_VOWEL_GUIDE,
  ey: {
    symbol: "ey",
    ipaSymbol: "eɪ",
    name: "Diphthong Vowel (前合双元音)",
    type: "diphthong",
    voiced: true,
    tonguePosition: "diphthong-ey",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "双元音。发音时先发 /e/ 音（类似于 bed 中的元音，口形半开，舌尖抵下齿），然后下颌自然收起，舌头向 /ɪ/ 的方向（类似于 pin 中的短音，舌位高而靠前）平滑移动。整个音程中发音是连续滑动的，音量前重后轻。",
    descriptionEn: "A diphthong vowel. Start with the mouth moderately open and the tongue in the mid-front position (as in 'bed'). Smoothly slide the jaw upwards and forward toward the /ɪ/ position (as in 'pin'), narrowing the mouth opening and fading out at the end.",
    tongueInstructions: "舌尖轻抵下齿。发音开始时舌前部抬高至中位，随后舌头顺畅地向前方和上方滑行抬起。",
    lipInstructions: "双唇略微扁平呈微笑状，发音过程中随着下颌合起而更加紧缩扁平。",
    airflowInstructions: "软腭上升堵住鼻腔通道，声带剧烈震动，气流由口腔顺畅呼出。",
    coachTips: "最常见的错误是发成类似 men (短 /e/) 的单音节音，导致 main 听起来像 men。一定要做出滑动，让发音有一个向 /ɪ/ 滑动的饱满尾音！",
    guideWord: "day",
    minimalPairs: [
      { word1: "main", word2: "men", ipa1: "meɪn", ipa2: "mɛn", note: "Contrast diphthong /eɪ/ with short monophthong /ɛ/" },
      { word1: "pain", word2: "pen", ipa1: "peɪn", ipa2: "pɛn", note: "Hear the vowel sliding upward in 'pain'" },
      { word1: "gate", word2: "get", ipa1: "geɪt", ipa2: "gɛt", note: "Double check you are not shortening the vowel in 'gate'" },
      { word1: "late", word2: "let", ipa1: "leɪt", ipa2: "lɛt", note: "Keep the vowel in 'late' prolonged and gliding" },
    ],
    practiceWords: ["main", "pain", "day", "face", "rain", "gate", "cake", "make"],
  },
  "eɪ": {
    // Alias mapping to support direct lookups in both systems
    symbol: "eɪ",
    ipaSymbol: "eɪ",
    name: "Diphthong Vowel (前合双元音)",
    type: "diphthong",
    voiced: true,
    tonguePosition: "diphthong-ey",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "双元音。发音时先发 /e/ 音（类似于 bed 中的元音，口形半开，舌尖抵下齿），然后下颌自然收起，舌头向 /ɪ/ 的方向（类似于 pin 中的短音，舌位高而靠前）平滑移动。整个音程中发音是连续滑动的，音量前重后轻。",
    descriptionEn: "A diphthong vowel. Start with the mouth moderately open and the tongue in the mid-front position (as in 'bed'). Smoothly slide the jaw upwards and forward toward the /ɪ/ position (as in 'pin'), narrowing the mouth opening and fading out at the end.",
    tongueInstructions: "舌尖轻抵下齿。发音开始时舌前部抬高至中位，随后舌头顺畅地向前方和上方滑行抬起。",
    lipInstructions: "双唇略微扁平呈微笑状，发音过程中随着下颌合起而更加紧缩扁平。",
    airflowInstructions: "软腭上升堵住鼻腔通道，声带剧烈震动，气流由口腔顺畅呼出。",
    coachTips: "最常见的错误是发成类似 men (短 /e/) 的单音节音，导致 main 听起来像 men。一定要做出滑动，让发音有一个向 /ɪ/ 滑动的饱满尾音！",
    guideWord: "day",
    minimalPairs: [
      { word1: "main", word2: "men", ipa1: "meɪn", ipa2: "mɛn", note: "Contrast diphthong /eɪ/ with short monophthong /ɛ/" },
      { word1: "pain", word2: "pen", ipa1: "peɪn", ipa2: "pɛn", note: "Hear the vowel sliding upward in 'pain'" },
      { word1: "gate", word2: "get", ipa1: "geɪt", ipa2: "gɛt", note: "Double check you are not shortening the vowel in 'gate'" },
      { word1: "late", word2: "let", ipa1: "leɪt", ipa2: "lɛt", note: "Keep the vowel in 'late' prolonged and gliding" },
    ],
    practiceWords: ["main", "pain", "day", "face", "rain", "gate", "cake", "make"],
  },
  // --- NASAL CONSONANTS ---
  m: {
    symbol: "m",
    ipaSymbol: "m",
    name: "Bilabial Nasal Consonant (双唇鼻音)",
    type: "nasal",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "closed",
    velum: "open",
    descriptionCn: "双唇闭合鼻音。双唇自然紧闭，舌头处于自然放松的中央位置。软腭下垂，使鼻腔通道彻底敞开。声带震动，气流受闭合的双唇阻碍，完全从鼻腔送出发出翁鸣音。",
    descriptionEn: "A bilabial nasal consonant. Place your lips completely together, keeping them soft and closed. Relax your tongue in the center of your mouth. Lower your velum (soft palate) to open the nasal passage. Vibrate your vocal cords and let the sound resonate through your nose.",
    tongueInstructions: "舌头完全平放放松，处于不与任何口腔软组织接触的自然状态。",
    lipInstructions: "双唇完全闭紧贴合，阻断口腔气流排出，直到音素发音结束释出。",
    airflowInstructions: "声带震动产生基音，软腭降低，将气流完全分流至鼻腔流出。",
    coachTips: "作为字头音时极易掌握，但作为词尾音时（如 team），有些人双唇没有彻底紧闭，而发成了类似 'n' 的音。确保词尾有明显的‘闭嘴’哼鸣声！",
    guideWord: "man",
    minimalPairs: [
      { word1: "team", word2: "teen", ipa1: "tiːm", ipa2: "tiːn", note: "Verify lips are fully closed at the end of 'team' and open for 'teen'" },
      { word1: "seem", word2: "seen", ipa1: "siːm", ipa2: "siːn", note: "Keep your lips closed at the end of 'seem'" },
    ],
    practiceWords: ["main", "man", "my", "more", "make", "team", "some", "game"],
  },
  n: {
    symbol: "n",
    ipaSymbol: "n",
    name: "Alveolar Nasal Consonant (齿龈鼻音)",
    type: "nasal",
    voiced: true,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "open",
    descriptionCn: "齿龈鼻音。双唇微开，舌尖抵住上齿龈（即上排门牙后侧硬邦邦的黏膜突起处），彻底封堵住口腔通道。软腭下垂，气流在声带震动的同时，被迫全部流向鼻腔逸出。",
    descriptionEn: "An alveolar nasal consonant. Slightly open your mouth and press the tip of your tongue firmly against the alveolar ridge (the hard bump behind your front teeth) to block air from leaving the mouth. Lower the velum, vibrate your vocal cords, and let the air escape through your nose.",
    tongueInstructions: "舌尖及舌侧边缘必须紧紧贴住上齿龈，形成半圆弧形的密闭屏障，确保没有任何气流漏入嘴唇处。",
    lipInstructions: "上下双唇微张（不要闭拢），牙齿轻轻拉开，露出阻碍气流的舌头前部。",
    airflowInstructions: "声带剧烈震动，软腭和悬雍垂下沉，让全部气流沿气管进入鼻腔由鼻孔送出。",
    coachTips: "在 main 这一类的词尾发音中，非英语母语者非常容易提前中断发音，或者没有将舌尖顶住上齿龈，导致鼻辅音彻底丢失，变成单纯的元音鼻化。记住，词尾必须稳稳地顶住上齿龈，给单词一个明确的 /n/ 收尾！",
    guideWord: "now",
    minimalPairs: [
      { word1: "main", word2: "may", ipa1: "meɪn", ipa2: "meɪ", note: "Contrast the nasal /n/ ending with the pure open vowel ending" },
      { word1: "line", word2: "lie", ipa1: "laɪn", ipa2: "laɪ", note: "Ensure your tongue clicks up to block the mouth at the end of 'line'" },
      { word1: "pin", word2: "ping", ipa1: "pɪn", ipa2: "pɪŋ", note: "Keep the tongue tip on the alveolar ridge, do not retract it to the throat" },
    ],
    practiceWords: ["main", "now", "no", "new", "nice", "on", "man", "sun", "fine", "ten"],
  },
  // --- OTHER COMMONLY DIFFICULT PHONEMES ---
  ng: {
    symbol: "ng",
    ipaSymbol: "ŋ",
    name: "Velar Nasal Consonant (软腭鼻音)",
    type: "nasal",
    voiced: true,
    tonguePosition: "velar",
    mouthOpening: "narrow",
    velum: "open",
    descriptionCn: "软腭鼻音。嘴唇张开，舌尖平放放松，舌后部（舌根）高高抬起，紧贴住软腭（口腔后顶部的软肉），封锁口腔通道。软腭自然垂下，声带颤动，气流由鼻孔流出。",
    descriptionEn: "A velar nasal consonant. Open your mouth slightly. Raise the back of your tongue to press firmly against the velum (soft palate) at the back of your mouth, blocking the oral passage. Lower the velum, vibrate your vocal cords, and let air flow through your nose.",
    tongueInstructions: "舌尖在下齿下方放松。舌头后部隆起贴靠上腭后部黏膜，彻底封死喉咙与口腔的连线。",
    lipInstructions: "双唇自然分开，保持中立状态，露出气流受阻的舌体。",
    airflowInstructions: "声带震动，阻断口部通路，气流改道自鼻腔后部逸出，产生低沉的鼻音。",
    coachTips: "千万不要把 sing 读成 sin！/ŋ/ (ng) 是舌后部顶住上腭，而 /n/ 是舌尖顶住前齿龈。另外也不要在尾音里发出了一个多余的 /g/（嘎）声。",
    guideWord: "sing",
    minimalPairs: [
      { word1: "sing", word2: "sin", ipa1: "sɪŋ", ipa2: "sɪn", note: "Back of tongue touch for 'sing' vs tongue tip touch for 'sin'" },
      { word1: "thing", word2: "thin", ipa1: "θɪŋ", ipa2: "θɪn", note: "Feel the pressure shift from back (throat) to front (teeth) at the end" },
    ],
    practiceWords: ["sing", "singing", "song", "long", "king", "ring", "bring", "young"],
  },
  "ŋ": {
    symbol: "ŋ",
    ipaSymbol: "ŋ",
    name: "Velar Nasal Consonant (软腭鼻音)",
    type: "nasal",
    voiced: true,
    tonguePosition: "velar",
    mouthOpening: "narrow",
    velum: "open",
    descriptionCn: "软腭鼻音。嘴唇张开，舌尖平放放松，舌后部（舌根）高高抬起，紧贴住软腭（口腔后顶部的软肉），封锁口腔通道。软腭自然垂下，声带颤动，气流由鼻孔流出。",
    descriptionEn: "A velar nasal consonant. Open your mouth slightly. Raise the back of your tongue to press firmly against the velum (soft palate) at the back of your mouth, blocking the oral passage. Lower the velum, vibrate your vocal cords, and let air flow through your nose.",
    tongueInstructions: "舌尖在下齿下方放松。舌头后部隆起贴靠上腭后部黏膜，彻底封死喉咙与口腔的连线。",
    lipInstructions: "双唇自然分开，保持中立状态，露出气流受阻的舌体。",
    airflowInstructions: "声带震动，阻断口部通路，气流改道自鼻腔后部逸出，产生低沉的鼻音。",
    coachTips: "千万不要把 sing 读成 sin！/ŋ/ (ng) 是舌后部顶住上腭，而 /n/ 是舌尖顶住前齿龈。另外也不要在尾音里发出了一个多余的 /g/（嘎）声。",
    guideWord: "sing",
    minimalPairs: [
      { word1: "sing", word2: "sin", ipa1: "sɪŋ", ipa2: "sɪn", note: "Back of tongue touch for 'sing' vs tongue tip touch for 'sin'" },
      { word1: "thing", word2: "thin", ipa1: "θɪŋ", ipa2: "θɪn", note: "Feel the pressure shift from back (throat) to front (teeth) at the end" },
    ],
    practiceWords: ["sing", "singing", "song", "long", "king", "ring", "bring", "young"],
  },
  th: {
    symbol: "th",
    ipaSymbol: "θ",
    name: "Voiceless Dental Fricative (清齿擦音)",
    type: "fricative",
    voiced: false,
    tonguePosition: "dental",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "清齿擦音（咬舌音）。双唇微开，舌尖平伸，轻轻放在上下齿之间（轻轻咬住舌尖）。软腭抬起封堵鼻腔。发音时用力向外吹气，让气流从舌头和上齿之间的极窄缝隙中摩擦挤出。声带不震动。",
    descriptionEn: "A voiceless dental fricative. Slightly open your mouth and stick the tip of your tongue out between your upper and lower teeth (gently bite it). Raise your velum to close the nose. Blow air out forcefully, letting it squeeze through the narrow gap between your tongue tip and upper teeth. Do not vibrate your vocal cords.",
    tongueInstructions: "舌尖前伸并稍微扁平，使其正好处于上下门齿的咬合缝隙之间，但不可以咬得过死，要留出气流通道。",
    lipInstructions: "嘴唇放松拉平，完全敞开门牙区域，露出咬住的舌尖。",
    airflowInstructions: "气流经过舌头顶端的微小阻碍发生剧烈摩擦产生呼呼气流。声带保持静止，不产生颤动。",
    coachTips: "最普遍的错误是把它发成类似 's' (sit) 或 'f' (fit) 的音。例如 thin 读成了 sin 或 fin。记得一定要把舌尖伸出来咬住！这需要夸张的练习！",
    guideWord: "thin",
    minimalPairs: [
      { word1: "thin", word2: "sin", ipa1: "θɪn", ipa2: "sɪn", note: "Put your tongue between your teeth for 'thin'; keep it inside for 'sin'" },
      { word1: "three", word2: "free", ipa1: "θriː", ipa2: "friː", note: "Use tongue-teeth for 'three'; use lower lip-teeth for 'free'" },
    ],
    practiceWords: ["thin", "thank", "think", "thought", "theme", "path", "both", "mouth", "earth"],
  },
  "θ": {
    symbol: "θ",
    ipaSymbol: "θ",
    name: "Voiceless Dental Fricative (清齿擦音)",
    type: "fricative",
    voiced: false,
    tonguePosition: "dental",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "清齿擦音（咬舌音）。双唇微开，舌尖平伸，轻轻放在上下齿之间（轻轻咬住舌尖）。软腭抬起封堵鼻腔。发音时用力向外吹气，让气流从舌头和上齿之间的极窄缝隙中摩擦挤出。声带不震动。",
    descriptionEn: "A voiceless dental fricative. Slightly open your mouth and stick the tip of your tongue out between your upper and lower teeth (gently bite it). Raise your velum to close the nose. Blow air out forcefully, letting it squeeze through the narrow gap between your tongue tip and upper teeth. Do not vibrate your vocal cords.",
    tongueInstructions: "舌尖前伸并稍微扁平，使其正好处于上下门齿的咬合缝隙之间，但不可以咬得过死，要留出气流通道。",
    lipInstructions: "嘴唇放松拉平，完全敞开门牙区域，露出咬住的舌尖。",
    airflowInstructions: "气流经过舌头顶端的微小阻碍发生剧烈摩擦产生呼呼气流。声带保持静止，不产生颤动。",
    coachTips: "最普遍的错误是把它发成类似 's' (sit) 或 'f' (fit) 的音。例如 thin 读成了 sin 或 fin。记得一定要把舌尖伸出来咬住！这需要夸张的练习！",
    guideWord: "thin",
    minimalPairs: [
      { word1: "thin", word2: "sin", ipa1: "θɪn", ipa2: "sɪn", note: "Put your tongue between your teeth for 'thin'; keep it inside for 'sin'" },
      { word1: "three", word2: "free", ipa1: "θriː", ipa2: "friː", note: "Use tongue-teeth for 'three'; use lower lip-teeth for 'free'" },
    ],
    practiceWords: ["thin", "thank", "think", "thought", "theme", "path", "both", "mouth", "earth"],
  },
  dh: {
    symbol: "dh",
    ipaSymbol: "ð",
    name: "Voiced Dental Fricative (浊齿擦音)",
    type: "fricative",
    voiced: true,
    tonguePosition: "dental",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "浊齿擦音（浊咬舌音）。双唇微开，舌尖平伸，轻轻放在上下门齿之间（轻轻咬住舌尖）。软腭抬起封堵鼻腔。发音时声带剧烈震动，同时让气流从舌面与上门牙齿缝间摩擦挤出。",
    descriptionEn: "A voiced dental fricative. Slightly open your mouth and place the tip of your tongue out between your upper and lower teeth (gently bite it). Raise the velum. Vibrate your vocal cords and let the voiced sound squeeze through the gap.",
    tongueInstructions: "舌面展平，舌尖极度放松伸出，搭在上下牙齿中间，保持轻微接触。",
    lipInstructions: "唇角对称微展，保持上下齿露露，使伸出的舌头处于清晰可见状态。",
    airflowInstructions: "声带震动产生底音，气流同时在齿缝间受挤压释放。声带必须保持全程抖动震鸣。",
    coachTips: "最常见的错误是发成 'd' (do) 或者 'z' (zoo)。例如 this 被读成 dis 或 zis。发音时要有震颤感，不要立刻把舌头缩回去！",
    guideWord: "this",
    minimalPairs: [
      { word1: "they", word2: "day", ipa1: "ðeɪ", ipa2: "deɪ", note: "Bite your tongue for 'they'; tap the roof of your mouth for 'day'" },
      { word1: "then", word2: "den", ipa1: "ðen", ipa2: "den", note: "Feel the smooth vibration on the teeth for 'then' vs a quick drop for 'den'" },
    ],
    practiceWords: ["this", "that", "they", "them", "then", "there", "father", "mother", "brother", "with"],
  },
  "ð": {
    symbol: "ð",
    ipaSymbol: "ð",
    name: "Voiced Dental Fricative (浊齿擦音)",
    type: "fricative",
    voiced: true,
    tonguePosition: "dental",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "浊齿擦音（浊咬舌音）。双唇微开，舌尖平伸，轻轻放在上下门齿之间（轻轻咬住舌尖）。软腭抬起封堵鼻腔。发音时声带剧烈震动，同时让气流从舌面与上门牙齿缝间摩擦挤出。",
    descriptionEn: "A voiced dental fricative. Slightly open your mouth and place the tip of your tongue out between your upper and lower teeth (gently bite it). Raise the velum. Vibrate your vocal cords and let the voiced sound squeeze through the gap.",
    tongueInstructions: "舌面展平，舌尖极度放松伸出，搭在上下牙齿中间，保持轻微接触。",
    lipInstructions: "唇角对称微展，保持上下齿露露，使伸出的舌头处于清晰可见状态。",
    airflowInstructions: "声带震动产生底音，气流同时在齿缝间受挤压释放。声带必须保持全程抖动震鸣。",
    coachTips: "最常见的错误是发成 'd' (do) 或者 'z' (zoo)。例如 this 被读成 dis 或 zis。发音时要有震颤感，不要立刻把舌头缩回去！",
    guideWord: "this",
    minimalPairs: [
      { word1: "they", word2: "day", ipa1: "ðeɪ", ipa2: "deɪ", note: "Bite your tongue for 'they'; tap the roof of your mouth for 'day'" },
      { word1: "then", word2: "den", ipa1: "ðen", ipa2: "den", note: "Feel the smooth vibration on the teeth for 'then' vs a quick drop for 'den'" },
    ],
    practiceWords: ["this", "that", "they", "them", "then", "there", "father", "mother", "brother", "with"],
  },
  // --- HIGH VOWELS ---
  i: {
    symbol: "i",
    ipaSymbol: "iː",
    name: "High Front Vowel (前高长元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "high-front",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "长元音（衣）。双唇向两旁扁平拉开（微笑嘴型），牙齿几乎靠拢。舌头前部向上腭前部抬起，高度仅次于半元音 /j/。舌尖轻抵下齿。声带震动，发音饱满而悠长。",
    descriptionEn: "A high front vowel. Pull the corners of your lips far back into a wide smile, with your teeth very close together. Raise the front of your tongue very high toward the roof of your mouth, close to the front teeth. Vibrate your vocal cords and make a long, stable sound.",
    tongueInstructions: "舌尖牢牢顶住下门牙内侧。舌面前端明显弓起，极度靠近上腭，舌两侧缘紧贴上臼齿内侧。",
    lipInstructions: "双唇强烈地向两侧扁平伸展，形成极具爆发力的极客微笑嘴角线，绝不放松。",
    airflowInstructions: "声带强烈振动，口腔形成极其狭长紧绷的发音通道，气流从中均匀流过。",
    coachTips: "注意区分长 /iː/ (see) 和短 /ɪ/ (sit)。/iː/ 的舌头更加紧绷、更高，嘴唇咧得更开，发音较长。千万别读成短音！",
    guideWord: "see",
    minimalPairs: [
      { word1: "feet", word2: "fit", ipa1: "fiːt", ipa2: "fɪt", note: "Tense your mouth for 'feet' (smile!) and relax it for 'fit'" },
      { word1: "seat", word2: "sit", ipa1: "siːt", ipa2: "sɪt", note: "Prolong the vowel in 'seat' vs keep it short and lax in 'sit'" },
    ],
    practiceWords: ["see", "she", "he", "we", "me", "keep", "feet", "quiet", "streets", "week"],
  },
  "iː": {
    symbol: "iː",
    ipaSymbol: "iː",
    name: "High Front Vowel (前高长元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "high-front",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "长元音（衣）。双唇向两旁扁平拉开（微笑嘴型），牙齿几乎靠拢。舌头前部向上腭前部抬起，高度仅次于半元音 /j/。舌尖轻抵下齿。声带震动，发音饱满而悠长。",
    descriptionEn: "A high front vowel. Pull the corners of your lips far back into a wide smile, with your teeth very close together. Raise the front of your tongue very high toward the roof of your mouth, close to the front teeth. Vibrate your vocal cords and make a long, stable sound.",
    tongueInstructions: "舌尖牢牢顶住下门牙内侧。舌面前端明显弓起，极度靠近上腭，舌两侧缘紧贴上臼齿内侧。",
    lipInstructions: "双唇强烈地向两侧扁平伸展，形成极具爆发力的极客微笑嘴角线，绝不放松。",
    airflowInstructions: "声带强烈振动，口腔形成极其狭长紧绷的发音通道，气流从中均匀流过。",
    coachTips: "注意区分长 /iː/ (see) 和短 /ɪ/ (sit)。/iː/ 的舌头更加紧绷、更高，嘴唇咧得更开，发音较长。千万别读成短音！",
    guideWord: "see",
    minimalPairs: [
      { word1: "feet", word2: "fit", ipa1: "fiːt", ipa2: "fɪt", note: "Tense your mouth for 'feet' (smile!) and relax it for 'fit'" },
      { word1: "seat", word2: "sit", ipa1: "siːt", ipa2: "sɪt", note: "Prolong the vowel in 'seat' vs keep it short and lax in 'sit'" },
    ],
    practiceWords: ["see", "she", "he", "we", "me", "keep", "feet", "quiet", "streets", "week"],
  },
  r: {
    symbol: "r",
    ipaSymbol: "r",
    name: "Alveolar Approximant Consonant (齿龈无擦通音)",
    type: "other",
    voiced: true,
    tonguePosition: "neutral", // will customize in rendering
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "齿龈无擦通音（卷舌音）。双唇稍扁且向外微翘（类似吹哨嘴型）。舌尖高抬朝向上齿龈后方（硬腭前部），舌身两侧收缩，使舌体略成凹槽。发音时气流从舌面凹槽与硬腭之间顺畅流出，舌尖绝对不可以接触口腔任何部位，且不能抖动！声带震动。",
    descriptionEn: "An alveolar approximant (English R). Round your lips slightly and push them out a bit. Curl the tip of your tongue back, pointing it toward the roof of your mouth (just behind the alveolar ridge). Make sure the tongue tip is floating and DOES NOT touch the roof or shake. Vibrate your vocal cords.",
    tongueInstructions: "舌头卷起，舌尖高悬并向内微缩，悬浮在口腔中部。绝对不能碰到牙齿或上腭！",
    lipInstructions: "双唇突出呈圆筒状或微扁小圆，增加口腔共鸣管的长度，创造出典型的 R 声。",
    airflowInstructions: "气流从隆起的舌两侧和悬空舌尖间的空间平稳送出，声带稳定震动。",
    coachTips: "非母语者容易把英语 /r/ 发成中文的“日”音（舌尖摩擦明显，带有辅音色彩），或者发成舌尖颤音（打滚）。确保舌尖悬空不动，完全没有多余的杂音和物理接触！",
    guideWord: "red",
    minimalPairs: [
      { word1: "red", word2: "led", ipa1: "red", ipa2: "led", note: "Curl your tongue back for 'red'; press the tip to your alveolar ridge for 'led'" },
      { word1: "right", word2: "light", ipa1: "raɪt", ipa2: "laɪt", note: "Floating tongue tip for 'right' vs physical touch-down for 'light'" },
    ],
    practiceWords: ["red", "rain", "right", "run", "room", "try", "street", "quiet", "write", "agree"],
  },
  l: {
    symbol: "l",
    ipaSymbol: "l",
    name: "Alveolar Lateral Consonant (齿龈边音)",
    type: "other",
    voiced: true,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "齿龈边音。发音时嘴微张，舌尖抵住上齿龈，封锁正前方的气流通道。声带震动，气流被迫从舌头身体两侧（边缘）分流而出，听起来十分清亮柔和。可分为字头清晰音 (Light L) 与字尾含混暗音 (Dark L)。",
    descriptionEn: "An alveolar lateral consonant. Slightly open your mouth. Press the tip of your tongue firmly against the alveolar ridge (the hard bump behind your upper teeth) to block front airflow. Vibrate your vocal cords and let the air flow smoothly over the sides (laterals) of your tongue.",
    tongueInstructions: "舌尖前端紧顶上齿龈。舌体肌肉平铺拉紧，两侧与磨牙拉开缝隙作为声音排放口。",
    lipInstructions: "双唇中性微张，嘴角微向上提，让两侧导流出的音波顺利散开。",
    airflowInstructions: "声带震动，气流由喉咙呼出后分为左、右两股，顺着磨牙和舌侧皮肤缝隙摩擦溢出。",
    coachTips: "在字尾（如 well, school）中，它叫做 Dark L。很多人会把它完全读成 'w' 或 'o' 音，例如 school 读成 /skuːo/。发 Dark L 时虽然舌尖不一定非要完全顶住上齿龈，但舌后部必须隆起，发出含糊的边音共鸣！",
    guideWord: "leg",
    minimalPairs: [
      { word1: "late", word2: "rate", ipa1: "leɪt", ipa2: "reɪt", note: "Press tongue for 'late' vs curl and float tongue for 'rate'" },
      { word1: "light", word2: "right", ipa1: "laɪt", ipa2: "raɪt", note: "Physical seal at alveolar ridge for 'light' vs suspended hover for 'right'" },
    ],
    practiceWords: ["leg", "light", "late", "look", "love", "walk", "plan", "quietly", "school", "well"],
  },
  z: {
    symbol: "z",
    ipaSymbol: "z",
    name: "Voiced Alveolar Fricative Consonant (齿龈浊擦音)",
    type: "fricative",
    voiced: true,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "齿龈浊擦音（摩擦音）。发音时双唇微张（呈微笑状），上下齿几乎靠拢但留微缝。舌尖抬起，极度靠近上齿龈，形成一条极窄的缝隙。声带剧烈震动，气流从舌尖与齿龈间的窄缝中挤出，发生剧烈摩擦，发出类似蜜蜂嗡嗡叫的摩擦音。",
    descriptionEn: "A voiced alveolar fricative. Slightly open your mouth in a gentle smile, bringing your teeth close together. Raise your tongue tip very close to the alveolar ridge (just behind your upper teeth) to form a narrow gap. Vibrate your vocal cords and squeeze air through this gap to produce a buzzing friction sound.",
    tongueInstructions: "舌尖向齿龈抬起但绝不能碰到它，两侧边缘贴住上臼齿，在舌中线形成狭窄的出气气道。",
    lipInstructions: "双唇向两侧自然拉开呈扁平状，类似微笑，露出牙齿。",
    airflowInstructions: "声带剧烈震动，气流由喉咙呼出，被迫通过舌尖形成的极窄沟槽，冲击门牙缝产生‘滋滋’磨擦声。",
    coachTips: "最常见的错误是舌尖碰到了齿龈，发成了 'd' 或 'j' 的爆破音（例如 zip 读成 dip）；或者声带没有震动，发成了清擦音 's' (zip 读成 sip)。发音时摸摸喉咙，确保声带有明显的麻木嗡鸣感！",
    guideWord: "zoo",
    minimalPairs: [
      { word1: "zip", word2: "sip", ipa1: "zɪp", ipa2: "sɪp", note: "Contrast voiced /z/ with voiceless /s/" },
      { word1: "buzz", word2: "bus", ipa1: "bʌz", ipa2: "bʌs", note: "Keep vocal cords vibrating until the very end of 'buzz'" },
    ],
    practiceWords: ["zoo", "zone", "zero", "buzz", "easy", "busy", "size", "please", "phrase"],
  },
  s: {
    symbol: "s",
    ipaSymbol: "s",
    name: "Voiceless Alveolar Fricative Consonant (齿龈清擦音)",
    type: "fricative",
    voiced: false,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "齿龈清擦音（嘶嘶音）。嘴唇扁平展开微露牙齿，上下齿极度靠拢但微拉开。舌尖高抬，靠近但不接触上齿龈，形成狭长的出气窄道。软腭抬起封闭鼻腔。发音时声带不震动，强气流从舌尖窄缝通道吹出，在门牙处发生嘶嘶擦音。",
    descriptionEn: "A voiceless alveolar fricative. Keep your lips spread in a smile and bring your teeth very close together. Raise the tip of your tongue near the alveolar ridge without touching it. Blow air out forcefully through this narrow channel, letting it hiss against your teeth. Do not vibrate your vocal cords.",
    tongueInstructions: "舌尖平指前方，极度接近门牙后侧的齿龈但不能触碰，使气流在此产生剧烈摩擦。",
    lipInstructions: "双唇呈扁平微展微笑状，上下门齿咬合微张，使空气容易喷射在齿面上。",
    airflowInstructions: "气流快速自喉部冲出，在口腔前段受窄缝挤压阻碍。声带必须保持完全放松静止。",
    coachTips: "如果发音时舌头伸出门牙外侧，会变成咬舌音 /θ/（清 thin）。舌尖必须乖乖留在门牙内侧！",
    guideWord: "sit",
    minimalPairs: [
      { word1: "sip", word2: "zip", ipa1: "sɪp", ipa2: "zɪp", note: "No vocal vibration for 'sip' vs buzzing vibration for 'zip'" },
      { word1: "sing", word2: "thing", ipa1: "sɪŋ", ipa2: "θɪŋ", note: "Keep your tongue inside for 'sing'; bite your tongue tip for 'thing'" },
    ],
    practiceWords: ["sit", "sing", "some", "see", "sun", "nice", "streets", "face", "place", "class"],
  },
};

const ADDITIONAL_PHONEME_GUIDES: Record<string, PhonemeGuide> = {
  p: {
    symbol: "p",
    ipaSymbol: "p",
    name: "Voiceless Bilabial Plosive (清双唇爆破音)",
    type: "plosive",
    voiced: false,
    tonguePosition: "neutral",
    mouthOpening: "closed",
    velum: "closed",
    descriptionCn: "清双唇爆破音。先把双唇完全闭合，口腔里短暂蓄气，然后突然打开双唇释放一小股气流。声带不震动，开头通常带明显送气。",
    descriptionEn: "A voiceless bilabial plosive. Close both lips completely, build a small pocket of air, then release it suddenly. Keep the vocal cords quiet; at the beginning of a stressed syllable it usually has a clear puff of air.",
    tongueInstructions: "舌头放松平放，不参与封闭；真正的阻塞来自双唇。",
    lipInstructions: "双唇先贴紧形成密封，再快速弹开。不要只轻轻擦过嘴唇。",
    airflowInstructions: "软腭抬起关闭鼻腔，气流在双唇后短暂蓄压后爆破释放。",
    coachTips: "练 pin 时在嘴前放一张纸，/p/ 应该能轻轻吹动纸；bin 的 /b/ 则没有这么强的送气。",
    guideWord: "pin",
    minimalPairs: [
      { word1: "pin", word2: "bin", ipa1: "pɪn", ipa2: "bɪn", note: "No voicing and stronger air for 'pin'; voicing for 'bin'" },
      { word1: "pat", word2: "bat", ipa1: "pæt", ipa2: "bæt", note: "Hold lips closed, then release without vocal vibration" },
    ],
    practiceWords: ["pin", "pay", "park", "people", "paper", "open", "stop", "help"],
  },
  b: {
    symbol: "b",
    ipaSymbol: "b",
    name: "Voiced Bilabial Plosive (浊双唇爆破音)",
    type: "plosive",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "closed",
    velum: "closed",
    descriptionCn: "浊双唇爆破音。双唇完全闭合后打开，声带在闭合和释放时保持震动。它比 /p/ 送气弱，重点是有低沉的嗓音震动。",
    descriptionEn: "A voiced bilabial plosive. Close both lips, keep vocal vibration active, then release the lips. Compared with /p/, the air burst is weaker and the voicing is the important cue.",
    tongueInstructions: "舌头自然放松，保持中立，不要向前顶。",
    lipInstructions: "双唇贴合后快速打开；释放时不要加很强的清气。",
    airflowInstructions: "软腭关闭鼻腔，声带震动，双唇打开时释放带声音的短爆破。",
    coachTips: "如果 bin 被听成 pin，通常是声带启动太晚或送气太强。先轻轻哼一声，再接 /b/。",
    guideWord: "bin",
    minimalPairs: [
      { word1: "bin", word2: "pin", ipa1: "bɪn", ipa2: "pɪn", note: "Start voicing immediately for 'bin'" },
      { word1: "bat", word2: "pat", ipa1: "bæt", ipa2: "pæt", note: "Keep the burst softer and voiced for 'bat'" },
    ],
    practiceWords: ["bin", "bad", "book", "about", "baby", "job", "cab", "brother"],
  },
  t: {
    symbol: "t",
    ipaSymbol: "t",
    name: "Voiceless Alveolar Plosive (清齿龈爆破音)",
    type: "plosive",
    voiced: false,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "清齿龈爆破音。舌尖抵住上门牙后的齿龈，短暂堵住气流，然后快速放开。声带不震动，词首重读位置常有明显送气。",
    descriptionEn: "A voiceless alveolar plosive. Touch the tongue tip to the alveolar ridge behind the upper teeth, hold the air briefly, then release quickly. Keep vocal cords quiet; initial stressed /t/ is usually aspirated.",
    tongueInstructions: "舌尖轻快抵住上齿龈，接触点要干净，不要卷到很后面。",
    lipInstructions: "双唇自然微开，保持放松，不要用嘴唇帮助爆破。",
    airflowInstructions: "气流在舌尖后方蓄积，舌尖离开齿龈时突然释放。",
    coachTips: "do 和 to 的差别不只是拼写。to 的 /t/ 要清、短、有气；do 的 /d/ 要有声带震动。",
    guideWord: "to",
    minimalPairs: [
      { word1: "to", word2: "do", ipa1: "tu", ipa2: "du", note: "No voicing and more air for 'to'; voicing for 'do'" },
      { word1: "ten", word2: "den", ipa1: "tɛn", ipa2: "dɛn", note: "Release the tongue cleanly without vocal vibration" },
    ],
    practiceWords: ["to", "ten", "time", "talk", "little", "letter", "cat", "right"],
  },
  d: {
    symbol: "d",
    ipaSymbol: "d",
    name: "Voiced Alveolar Plosive (浊齿龈爆破音)",
    type: "plosive",
    voiced: true,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "浊齿龈爆破音。舌尖抵住齿龈形成短暂封闭，同时声带震动，然后舌尖快速离开。送气比 /t/ 弱。",
    descriptionEn: "A voiced alveolar plosive. Touch the tongue tip to the alveolar ridge, keep vocal vibration active, then release. The burst is softer and less aspirated than /t/.",
    tongueInstructions: "舌尖贴住上齿龈后迅速放开，动作短促但有声音。",
    lipInstructions: "嘴唇自然微开，不要闭唇或噘嘴。",
    airflowInstructions: "声带震动，气流被舌尖短暂挡住后释放。",
    coachTips: "如果 day 听起来像 they，要避免把舌尖伸到牙齿之间；/d/ 是舌尖顶齿龈，不是咬舌音。",
    guideWord: "do",
    minimalPairs: [
      { word1: "do", word2: "to", ipa1: "du", ipa2: "tu", note: "Voicing begins early in 'do'" },
      { word1: "day", word2: "they", ipa1: "deɪ", ipa2: "ðeɪ", note: "Tongue taps the ridge for 'day'; tongue between teeth for 'they'" },
    ],
    practiceWords: ["do", "day", "did", "dinner", "under", "middle", "red", "said"],
  },
  k: {
    symbol: "k",
    ipaSymbol: "k",
    name: "Voiceless Velar Plosive (清软腭爆破音)",
    type: "plosive",
    voiced: false,
    tonguePosition: "velar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "清软腭爆破音。舌后部抬起贴住软腭，堵住气流，然后突然放开。声带不震动，词首通常带送气。",
    descriptionEn: "A voiceless velar plosive. Raise the back of the tongue to touch the soft palate, block the air, then release suddenly. Keep the vocal cords quiet; initial /k/ often has aspiration.",
    tongueInstructions: "舌尖放松，舌后部向上抬起封住口腔后部。",
    lipInstructions: "双唇根据邻近元音自然调整，不要把 /k/ 做成喉咙挤压。",
    airflowInstructions: "气流在舌后部后方蓄压，舌后部放开时爆破。",
    coachTips: "key 不要发成 gee。/k/ 没有声带震动，释放时有更清楚的气流。",
    guideWord: "key",
    minimalPairs: [
      { word1: "key", word2: "gee", ipa1: "ki", ipa2: "gi", note: "No voicing and more air for 'key'" },
      { word1: "coat", word2: "goat", ipa1: "koʊt", ipa2: "goʊt", note: "Keep /k/ voiceless at the start" },
    ],
    practiceWords: ["key", "cat", "keep", "cake", "quickly", "back", "work", "country"],
  },
  g: {
    symbol: "g",
    ipaSymbol: "g",
    name: "Voiced Velar Plosive (浊软腭爆破音)",
    type: "plosive",
    voiced: true,
    tonguePosition: "velar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "浊软腭爆破音。舌后部贴住软腭后释放，同时声带震动。它比 /k/ 送气弱，声音更厚。",
    descriptionEn: "A voiced velar plosive. Raise the back of the tongue to the soft palate and release while vibrating the vocal cords. It is less aspirated and more voiced than /k/.",
    tongueInstructions: "舌后部封闭口腔后方，舌尖保持放松。",
    lipInstructions: "嘴唇自然打开，跟随后面的元音形状。",
    airflowInstructions: "声带先启动，气流在软腭闭合处释放成短爆破。",
    coachTips: "如果 get 听起来像 cat，先保证喉咙里有 /g/ 的震动，再打开舌后部。",
    guideWord: "get",
    minimalPairs: [
      { word1: "get", word2: "cat", ipa1: "gɛt", ipa2: "kæt", note: "Voiced back-tongue release for 'get'" },
      { word1: "goat", word2: "coat", ipa1: "goʊt", ipa2: "koʊt", note: "Keep vocal vibration in 'goat'" },
    ],
    practiceWords: ["get", "go", "good", "again", "bigger", "dog", "bag", "great"],
  },
  f: {
    symbol: "f",
    ipaSymbol: "f",
    name: "Voiceless Labiodental Fricative (清唇齿擦音)",
    type: "fricative",
    voiced: false,
    tonguePosition: "neutral",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "清唇齿擦音。上门牙轻触下唇内侧，留出窄缝，让气流摩擦通过。声带不震动。",
    descriptionEn: "A voiceless labiodental fricative. Touch the upper teeth lightly to the inside of the lower lip and blow air through the narrow gap. Keep the vocal cords quiet.",
    tongueInstructions: "舌头自然放松，不参与摩擦。",
    lipInstructions: "下唇轻轻抬向上齿，不要咬死，要留细小气道。",
    airflowInstructions: "气流从唇齿之间持续摩擦吹出，没有声带震动。",
    coachTips: "free 不是 three。/f/ 用唇齿，/θ/ 用舌尖和牙齿。",
    guideWord: "fit",
    minimalPairs: [
      { word1: "free", word2: "three", ipa1: "fri", ipa2: "θri", note: "Lower lip to teeth for 'free'; tongue tip for 'three'" },
      { word1: "fan", word2: "van", ipa1: "fæn", ipa2: "væn", note: "No throat vibration for 'fan'" },
    ],
    practiceWords: ["fit", "free", "face", "after", "office", "life", "if", "before"],
  },
  v: {
    symbol: "v",
    ipaSymbol: "v",
    name: "Voiced Labiodental Fricative (浊唇齿擦音)",
    type: "fricative",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "浊唇齿擦音。上齿轻触下唇，同时声带震动，让气流从唇齿缝中持续摩擦通过。",
    descriptionEn: "A voiced labiodental fricative. Touch the upper teeth lightly to the lower lip while vibrating the vocal cords. Let the air continue through the lip-teeth gap.",
    tongueInstructions: "舌头自然，不要向前顶或卷起。",
    lipInstructions: "下唇轻贴上齿，保持持续摩擦，不要爆破成 /b/。",
    airflowInstructions: "声带震动，气流从唇齿之间连续流出。",
    coachTips: "very 如果听成 berry，说明双唇闭合了。/v/ 必须是牙齿贴下唇，而不是双唇合上。",
    guideWord: "van",
    minimalPairs: [
      { word1: "van", word2: "fan", ipa1: "væn", ipa2: "fæn", note: "Keep vocal vibration for 'van'" },
      { word1: "very", word2: "berry", ipa1: "vɛri", ipa2: "bɛri", note: "Use teeth-lip friction, not closed lips" },
    ],
    practiceWords: ["van", "very", "visit", "seven", "over", "have", "give", "every"],
  },
  h: {
    symbol: "h",
    ipaSymbol: "h",
    name: "Voiceless Glottal Fricative (清喉擦音)",
    type: "fricative",
    voiced: false,
    tonguePosition: "neutral",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "清喉擦音。口腔形状直接准备好后面的元音，从喉部轻轻送出一口无声气流。舌头和嘴唇不制造明显阻碍。",
    descriptionEn: "A voiceless glottal fricative. Shape the mouth for the following vowel and let a gentle breath pass from the throat. The tongue and lips do not make a tight obstruction.",
    tongueInstructions: "舌头跟随后面的元音位置，不要顶住任何位置。",
    lipInstructions: "嘴唇提前摆出后面元音的口形，例如 he 的微笑口形或 hot 的开口。",
    airflowInstructions: "声门处产生轻微气流摩擦，声带不震动。",
    coachTips: "he 不要漏掉 /h/ 变成 ee；但也不要用力挤喉咙。像轻轻哈气一样开始。",
    guideWord: "hat",
    minimalPairs: [
      { word1: "heat", word2: "eat", ipa1: "hit", ipa2: "it", note: "Add a gentle breath before the vowel in 'heat'" },
      { word1: "hat", word2: "at", ipa1: "hæt", ipa2: "æt", note: "Do not drop the initial /h/" },
    ],
    practiceWords: ["hat", "he", "has", "have", "behind", "perhaps", "ahead", "who"],
  },
  "ʃ": {
    symbol: "ʃ",
    ipaSymbol: "ʃ",
    name: "Voiceless Postalveolar Fricative (清后齿龈擦音)",
    type: "fricative",
    voiced: false,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "清后齿龈擦音。舌前部抬向齿龈后方，嘴唇略收圆，气流从较宽的通道摩擦通过，声音像 sh。",
    descriptionEn: "A voiceless postalveolar fricative. Raise the front of the tongue just behind the alveolar ridge, slightly round the lips, and let air pass with a broad sh-like friction.",
    tongueInstructions: "舌尖不要贴住齿龈，舌前部靠后形成宽而浅的摩擦通道。",
    lipInstructions: "双唇略微向前收圆，区别于 /s/ 的扁平微笑口形。",
    airflowInstructions: "声带不震动，气流持续通过舌前部形成柔和摩擦。",
    coachTips: "ship 不要读成 sip。/ʃ/ 的舌位更靠后，嘴唇更圆。",
    guideWord: "ship",
    minimalPairs: [
      { word1: "ship", word2: "sip", ipa1: "ʃɪp", ipa2: "sɪp", note: "Move the tongue slightly back and round lips for 'ship'" },
      { word1: "she", word2: "see", ipa1: "ʃi", ipa2: "si", note: "Use sh friction, not sharp /s/" },
    ],
    practiceWords: ["ship", "she", "show", "sure", "machine", "finish", "wish", "English"],
  },
  "tʃ": {
    symbol: "tʃ",
    ipaSymbol: "tʃ",
    name: "Voiceless Affricate (清塞擦音)",
    type: "other",
    voiced: false,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "清塞擦音。先像 /t/ 一样用舌前部堵住气流，然后不要完全爆开，而是接成 /ʃ/ 的摩擦。声带不震动。",
    descriptionEn: "A voiceless affricate. Start with a /t/-like closure, then release into /ʃ/-like friction instead of a plain burst. Keep the vocal cords quiet.",
    tongueInstructions: "舌前部先封闭齿龈后方，随后向后放松成 sh 的窄通道。",
    lipInstructions: "双唇略微收圆，帮助形成 ch 的后部摩擦。",
    airflowInstructions: "先蓄气，再以持续摩擦方式释放，不能只发成单独的 /t/。",
    coachTips: "cheap 不要读成 sheep 或 jeep。它既有开头的阻塞，又没有 /dʒ/ 的声带震动。",
    guideWord: "chin",
    minimalPairs: [
      { word1: "cheap", word2: "sheep", ipa1: "tʃip", ipa2: "ʃip", note: "Add a stop before the sh friction in 'cheap'" },
      { word1: "chin", word2: "gin", ipa1: "tʃɪn", ipa2: "dʒɪn", note: "Keep 'chin' voiceless" },
    ],
    practiceWords: ["chin", "cheap", "chair", "choose", "teacher", "watch", "which", "much"],
  },
  "dʒ": {
    symbol: "dʒ",
    ipaSymbol: "dʒ",
    name: "Voiced Affricate (浊塞擦音)",
    type: "other",
    voiced: true,
    tonguePosition: "alveolar",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "浊塞擦音。先像 /d/ 一样封闭，再接成 /ʒ/ 类似的摩擦，同时声带震动。它是 jam, job 的开头音。",
    descriptionEn: "A voiced affricate. Start with a /d/-like closure, then release into a /ʒ/-like friction while keeping vocal vibration active. This is the initial sound in 'jam' and 'job'.",
    tongueInstructions: "舌前部先封住齿龈后方，再缓慢释放成带声摩擦。",
    lipInstructions: "双唇略微向前收圆，不要变成纯 /d/。",
    airflowInstructions: "声带震动贯穿封闭和摩擦释放。",
    coachTips: "jam 不要读成 zam。/dʒ/ 开头有一个小小的阻塞，不是直接擦出来。",
    guideWord: "jam",
    minimalPairs: [
      { word1: "jam", word2: "sham", ipa1: "dʒæm", ipa2: "ʃæm", note: "Add voiced stop closure for 'jam'" },
      { word1: "gin", word2: "chin", ipa1: "dʒɪn", ipa2: "tʃɪn", note: "Keep vocal vibration for 'gin'" },
    ],
    practiceWords: ["jam", "job", "just", "large", "engineer", "page", "bridge", "change"],
  },
  w: {
    symbol: "w",
    ipaSymbol: "w",
    name: "Voiced Labial-Velar Glide (浊圆唇滑音)",
    type: "other",
    voiced: true,
    tonguePosition: "high-back",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "圆唇滑音。双唇先收圆向前，舌后部抬高，然后快速滑向后面的元音。它不是 /v/，牙齿不能碰下唇。",
    descriptionEn: "A voiced labial-velar glide. Round and project the lips, raise the back of the tongue, then glide quickly into the following vowel. It is not /v/; the teeth should not touch the lower lip.",
    tongueInstructions: "舌后部向软腭方向抬起，随后顺滑进入下一个元音。",
    lipInstructions: "双唇明显收圆并向前，再快速打开到后续元音。",
    airflowInstructions: "声带震动，气流无摩擦地通过圆唇通道。",
    coachTips: "wet 不要读成 vet。/w/ 是圆唇滑过去，/v/ 是上齿摩擦下唇。",
    guideWord: "wet",
    minimalPairs: [
      { word1: "wet", word2: "vet", ipa1: "wɛt", ipa2: "vɛt", note: "Round lips for 'wet'; teeth-lip friction for 'vet'" },
      { word1: "wine", word2: "vine", ipa1: "waɪn", ipa2: "vaɪn", note: "No lower-lip bite for 'wine'" },
    ],
    practiceWords: ["wet", "we", "will", "word", "walk", "away", "twice", "quiet"],
  },
  j: {
    symbol: "j",
    ipaSymbol: "j",
    name: "Palatal Glide (硬腭滑音)",
    type: "other",
    voiced: true,
    tonguePosition: "high-front",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "硬腭滑音，也就是 yes 开头的 y 音。舌前部接近硬腭，像短暂的 /i/，然后迅速滑入后面的元音。",
    descriptionEn: "A palatal glide, the y sound at the start of 'yes'. Raise the front of the tongue near the hard palate, like a very short /i/, then glide into the following vowel.",
    tongueInstructions: "舌前部高高抬起接近硬腭，但不要摩擦或堵住。",
    lipInstructions: "双唇根据后面的元音自然变化；不要加 /dʒ/ 的阻塞。",
    airflowInstructions: "声带震动，气流顺滑通过口腔前部。",
    coachTips: "yes 不要读成 jess。/j/ 没有 /dʒ/ 的爆破开头。",
    guideWord: "yes",
    minimalPairs: [
      { word1: "yes", word2: "Jess", ipa1: "jɛs", ipa2: "dʒɛs", note: "No stop closure for 'yes'" },
      { word1: "yet", word2: "jet", ipa1: "jɛt", ipa2: "dʒɛt", note: "Glide smoothly for 'yet'" },
    ],
    practiceWords: ["yes", "you", "young", "year", "yellow", "beyond", "yesterday", "use"],
  },
  "ɪ": {
    symbol: "ɪ",
    ipaSymbol: "ɪ",
    name: "Short High Front Vowel (短前高元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "high-front",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "短前高元音。舌前部抬高但比 /iː/ 放松，嘴角不要咧得太紧。声音短、轻、松，像 pin, sit 里的元音。",
    descriptionEn: "A short high front vowel. Raise the front of the tongue, but keep it laxer and lower than /iː/. The lips are lightly spread, and the sound is short and relaxed.",
    tongueInstructions: "舌尖靠近下齿，舌前部抬起但不要绷紧到 /iː/ 的高度。",
    lipInstructions: "嘴唇轻微展开，避免过度微笑。",
    airflowInstructions: "声带震动，气流平稳通过口腔。",
    coachTips: "sit 不要说成 seat。/ɪ/ 更短、更松；/iː/ 更长、更紧。",
    guideWord: "pin",
    minimalPairs: [
      { word1: "sit", word2: "seat", ipa1: "sɪt", ipa2: "sit", note: "Short relaxed vowel in 'sit'; long tense vowel in 'seat'" },
      { word1: "fit", word2: "feet", ipa1: "fɪt", ipa2: "fit", note: "Do not stretch 'fit'" },
    ],
    practiceWords: ["pin", "sit", "fit", "this", "big", "little", "visit", "English"],
  },
  "ʊ": {
    symbol: "ʊ",
    ipaSymbol: "ʊ",
    name: "Short High Back Vowel (短后高元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "high-back",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "短后高元音。舌后部抬高但保持放松，双唇轻微收圆。它比 /u/ 更短、更松，像 foot, good 的元音。",
    descriptionEn: "A short high back vowel. Raise the back of the tongue but keep it relaxed. Lightly round the lips. It is shorter and laxer than /u/.",
    tongueInstructions: "舌后部抬起但不要绷紧，不要向前滑。",
    lipInstructions: "双唇轻微收圆，不要像 /u/ 那样强烈噘嘴。",
    airflowInstructions: "声带震动，气流稳定通过圆唇口腔。",
    coachTips: "foot 不要读成 food。/ʊ/ 更短，嘴唇更放松。",
    guideWord: "foot",
    minimalPairs: [
      { word1: "full", word2: "fool", ipa1: "fʊl", ipa2: "ful", note: "Short relaxed vowel in 'full'" },
      { word1: "pull", word2: "pool", ipa1: "pʊl", ipa2: "pul", note: "Do not lengthen 'pull'" },
    ],
    practiceWords: ["foot", "good", "look", "book", "put", "could", "would", "full"],
  },
  u: {
    symbol: "u",
    ipaSymbol: "uː",
    name: "High Back Rounded Vowel (后高圆唇长元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "high-back",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "后高圆唇长元音。舌后部高高抬起，双唇收圆向前，声音较长且稳定，像 too, blue。",
    descriptionEn: "A high back rounded vowel. Raise the back of the tongue high, round and project the lips, and hold the sound steadily as in 'too' or 'blue'.",
    tongueInstructions: "舌后部向软腭抬起，舌尖放松在下方。",
    lipInstructions: "双唇收圆向前，但不要用力到僵硬。",
    airflowInstructions: "声带震动，气流通过狭窄圆唇通道。",
    coachTips: "too 不要读成 toe。/u/ 的嘴唇更圆，舌位更高后。",
    guideWord: "too",
    minimalPairs: [
      { word1: "fool", word2: "full", ipa1: "ful", ipa2: "fʊl", note: "Hold /u/ longer and tighter in 'fool'" },
      { word1: "Luke", word2: "look", ipa1: "luk", ipa2: "lʊk", note: "Round more and lengthen for 'Luke'" },
    ],
    practiceWords: ["too", "you", "blue", "school", "soon", "through", "move", "June"],
  },
  "ə": {
    symbol: "ə",
    ipaSymbol: "ə",
    name: "Schwa (中央弱读元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "中央弱读元音。嘴巴和舌头都放松，声音短、轻、不重读，像 about 开头的 a。",
    descriptionEn: "The schwa, a reduced central vowel. Keep the jaw, tongue, and lips relaxed. The sound is short, light, and unstressed, as in the first vowel of 'about'.",
    tongueInstructions: "舌头放在口腔中央，不向前后高低明显移动。",
    lipInstructions: "双唇自然微开，不收圆也不横向拉紧。",
    airflowInstructions: "声带轻微震动，气流自然通过。",
    coachTips: "弱读音节不要发得太完整。about 的第一个音不是清晰的 /æ/，而是很轻的 /ə/。",
    guideWord: "about",
    minimalPairs: [
      { word1: "about", word2: "a bat", ipa1: "əbɑʊt", ipa2: "ə bæt", note: "Keep the first vowel weak and central" },
      { word1: "sofa", word2: "so far", ipa1: "soʊfə", ipa2: "soʊ fɑɹ", note: "Final schwa is short and relaxed" },
    ],
    practiceWords: ["about", "again", "away", "sofa", "teacher", "support", "today", "letter"],
  },
  "ʌ": {
    symbol: "ʌ",
    ipaSymbol: "ʌ",
    name: "Open-mid Central Vowel (短中央元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "短中央元音。嘴巴自然打开，舌头放在中间偏低位置，声音短而清楚，像 cup, sun。",
    descriptionEn: "A short open-mid central vowel. Open the jaw naturally and keep the tongue central and slightly low. The sound is short and clear, as in 'cup' and 'sun'.",
    tongueInstructions: "舌体放松在中央，不要向后缩成 /ɑ/，也不要太高变成 /ə/。",
    lipInstructions: "双唇自然张开，不圆唇。",
    airflowInstructions: "声带震动，气流平稳通过中等开口。",
    coachTips: "cup 不要读成 cap 或 cop。保持中央、短促、非圆唇。",
    guideWord: "cup",
    minimalPairs: [
      { word1: "cup", word2: "cap", ipa1: "kʌp", ipa2: "kæp", note: "Central tongue for 'cup'; front and wider for 'cap'" },
      { word1: "luck", word2: "lock", ipa1: "lʌk", ipa2: "lɑk", note: "Do not pull the vowel too far back" },
    ],
    practiceWords: ["cup", "sun", "much", "country", "number", "love", "under", "done"],
  },
  "æ": {
    symbol: "æ",
    ipaSymbol: "æ",
    name: "Low Front Vowel (低前元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "low-front",
    mouthOpening: "wide",
    velum: "closed",
    descriptionCn: "低前元音。嘴巴张大，舌前部低而靠前，嘴唇展开。像 cat, man 里的元音。",
    descriptionEn: "A low front vowel. Open the mouth wide, keep the front of the tongue low and forward, and spread the lips slightly. This is the vowel in 'cat' and 'man'.",
    tongueInstructions: "舌尖靠近下齿，舌前部低放但保持靠前。",
    lipInstructions: "双唇自然向两侧打开，口腔开度较大。",
    airflowInstructions: "声带震动，气流通过较大的前部口腔空间。",
    coachTips: "man 不要变成 men。/æ/ 开口更大，舌位更低。",
    guideWord: "cat",
    minimalPairs: [
      { word1: "man", word2: "men", ipa1: "mæn", ipa2: "mɛn", note: "Open wider and lower for 'man'" },
      { word1: "cat", word2: "cut", ipa1: "kæt", ipa2: "kʌt", note: "Front and wide for 'cat'; central for 'cut'" },
    ],
    practiceWords: ["cat", "man", "has", "that", "back", "family", "travel", "practice"],
  },
  "ɑ": {
    symbol: "ɑ",
    ipaSymbol: "ɑ",
    name: "Low Back Vowel (低后元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "low-back",
    mouthOpening: "wide",
    velum: "closed",
    descriptionCn: "低后元音。嘴巴张大，舌头后缩且放低，声音宽而稳，像 father, car 中的 a。",
    descriptionEn: "A low back vowel. Open the mouth wide, retract and lower the tongue, and keep the sound broad and steady, as in 'father' or the vowel in 'car'.",
    tongueInstructions: "舌体向后放低，舌尖不顶前齿。",
    lipInstructions: "嘴唇自然张开，不明显圆唇。",
    airflowInstructions: "声带震动，气流通过开阔的后部口腔。",
    coachTips: "hot/car 的美式 /ɑ/ 不要发成前面的 /æ/。感觉声音从口腔后方打开。",
    guideWord: "father",
    minimalPairs: [
      { word1: "cot", word2: "cat", ipa1: "kɑt", ipa2: "kæt", note: "Back vowel for 'cot'; front vowel for 'cat'" },
      { word1: "father", word2: "feather", ipa1: "fɑðɚ", ipa2: "fɛðɚ", note: "Open back vowel in 'father'" },
    ],
    practiceWords: ["father", "car", "hot", "lot", "not", "want", "body", "office"],
  },
  "ɔ": {
    symbol: "ɔ",
    ipaSymbol: "ɔ",
    name: "Mid Back Rounded Vowel (后中圆唇元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "mid-back",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "后中圆唇元音。舌后部抬到中位，嘴唇轻微收圆，声音比 /ɑ/ 更圆、更靠后，像 saw, thought 中的 aw。",
    descriptionEn: "A mid back rounded vowel. Raise the back of the tongue to mid height and lightly round the lips. It is rounder and less open than /ɑ/, as in 'saw' or 'thought'.",
    tongueInstructions: "舌后部抬起到中位，不要完全放低。",
    lipInstructions: "双唇轻微收圆，口腔保持中等开度。",
    airflowInstructions: "声带震动，气流经过后部圆唇口形。",
    coachTips: "walk 不要读得太像 work。/ɔ/ 是圆而开，不带 r-colored 卷舌。",
    guideWord: "saw",
    minimalPairs: [
      { word1: "saw", word2: "so", ipa1: "sɔ", ipa2: "soʊ", note: "Hold a steady rounded vowel in 'saw'; glide in 'so'" },
      { word1: "walk", word2: "work", ipa1: "wɔk", ipa2: "wɝk", note: "No r-coloring in 'walk'" },
    ],
    practiceWords: ["saw", "thought", "walk", "talk", "also", "small", "Australia", "because"],
  },
  "aɪ": {
    symbol: "aɪ",
    ipaSymbol: "aɪ",
    name: "Diphthong Vowel (开合双元音)",
    type: "diphthong",
    voiced: true,
    tonguePosition: "diphthong-ay",
    mouthOpening: "wide",
    velum: "closed",
    descriptionCn: "双元音。先从开口较大的 /a/ 开始，再向短 /ɪ/ 的高前位置滑动。像 my, time 中的元音。",
    descriptionEn: "A diphthong. Start with an open /a/-like vowel, then glide upward and forward toward /ɪ/. This is the vowel in 'my' and 'time'.",
    tongueInstructions: "起点低而开，随后舌前部向上、向前滑动。",
    lipInstructions: "嘴巴先张大，结尾逐渐收窄并略微展开。",
    airflowInstructions: "声带持续震动，气流稳定通过，重点是完整滑动。",
    coachTips: "time 不要只发成 tahm。必须听到从开口音滑向 /ɪ/ 的尾巴。",
    guideWord: "my",
    minimalPairs: [
      { word1: "my", word2: "ma", ipa1: "maɪ", ipa2: "mɑ", note: "Add the upward glide in 'my'" },
      { word1: "time", word2: "Tom", ipa1: "taɪm", ipa2: "tɑm", note: "Do not stop at the open vowel" },
    ],
    practiceWords: ["my", "time", "I", "like", "right", "find", "arrive", "quiet"],
  },
  "aʊ": {
    symbol: "aʊ",
    ipaSymbol: "aʊ",
    name: "Diphthong Vowel (开后合双元音)",
    type: "diphthong",
    voiced: true,
    tonguePosition: "diphthong-aw",
    mouthOpening: "wide",
    velum: "closed",
    descriptionCn: "双元音。先从较大的开口元音开始，再向后高圆唇的 /ʊ/ 滑动，像 cow, now。",
    descriptionEn: "A diphthong. Start open, then glide back and upward toward a rounded /ʊ/ position, as in 'cow' and 'now'.",
    tongueInstructions: "舌头从低位开始，向后上方滑动。",
    lipInstructions: "嘴巴先张开，结尾双唇逐渐收圆。",
    airflowInstructions: "声带持续震动，元音要有明显的移动轨迹。",
    coachTips: "now 不要读成 na。结尾要收圆，像轻轻靠近 /ʊ/。",
    guideWord: "cow",
    minimalPairs: [
      { word1: "now", word2: "nah", ipa1: "naʊ", ipa2: "nɑ", note: "Round and close at the end of 'now'" },
      { word1: "loud", word2: "lod", ipa1: "laʊd", ipa2: "lɑd", note: "Keep the glide in 'loud'" },
    ],
    practiceWords: ["cow", "now", "how", "about", "out", "down", "found", "house"],
  },
  "oʊ": {
    symbol: "oʊ",
    ipaSymbol: "oʊ",
    name: "Diphthong Vowel (后合双元音)",
    type: "diphthong",
    voiced: true,
    tonguePosition: "diphthong-ow",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "双元音。先从中后圆唇元音开始，再向更高、更圆的 /ʊ/ 滑动。像 go, home。",
    descriptionEn: "A diphthong. Start with a mid back rounded vowel, then glide toward a higher, tighter /ʊ/-like ending, as in 'go' and 'home'.",
    tongueInstructions: "舌后部从中位向高位滑动。",
    lipInstructions: "双唇从轻圆逐渐收得更圆更窄。",
    airflowInstructions: "声带持续震动，气流稳定，元音结尾要收住。",
    coachTips: "go 不要读成单纯的 /gɔ/。美式英语里常有明显的收圆滑动。",
    guideWord: "go",
    minimalPairs: [
      { word1: "go", word2: "gaw", ipa1: "goʊ", ipa2: "gɔ", note: "Glide upward and rounder in 'go'" },
      { word1: "coat", word2: "caught", ipa1: "koʊt", ipa2: "kɔt", note: "Hold steady for 'caught'; glide for 'coat'" },
    ],
    practiceWords: ["go", "home", "no", "so", "only", "open", "phone", "road"],
  },
  ju: {
    symbol: "ju",
    ipaSymbol: "ju",
    name: "Yod + High Back Vowel (滑音加圆唇元音)",
    type: "diphthong",
    voiced: true,
    tonguePosition: "diphthong-ow",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "由 /j/ 滑音接 /u/ 组成。先像 yes 的 y 一样舌前部抬高，然后快速滑到圆唇的 /u/。像 use, music。",
    descriptionEn: "A /j/ glide followed by /u/. Start with the y-like tongue position from 'yes', then glide quickly into the rounded /u/ vowel, as in 'use' and 'music'.",
    tongueInstructions: "先舌前部抬高，再滑向舌后部高位。",
    lipInstructions: "开始较放松，随后双唇明显收圆。",
    airflowInstructions: "声带持续震动，滑音和元音之间不要断开。",
    coachTips: "use 不要读成 ooze。词首需要一个轻快的 /j/ 滑音。",
    guideWord: "use",
    minimalPairs: [
      { word1: "use", word2: "ooze", ipa1: "juz", ipa2: "uz", note: "Add the y-glide before /u/ in 'use'" },
      { word1: "cute", word2: "coot", ipa1: "kjut", ipa2: "kut", note: "Keep the /j/ glide in 'cute'" },
    ],
    practiceWords: ["use", "you", "music", "usual", "university", "cute", "few", "new"],
  },
  "ɔɹ": {
    symbol: "ɔɹ",
    ipaSymbol: "ɔɹ",
    name: "R-colored Back Vowel (后元音加 R 色彩)",
    type: "vowel",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "后圆元音接 R 色彩。先有 /ɔ/ 的圆而开的位置，再把舌头后收形成英语 /r/ 的共鸣。像 for, more。",
    descriptionEn: "An r-colored back vowel sequence. Start with a rounded /ɔ/-like vowel, then retract the tongue into English /r/ resonance, as in 'for' and 'more'.",
    tongueInstructions: "先舌后部中位，再舌身后收，舌尖悬空不要碰上腭。",
    lipInstructions: "嘴唇保持轻微圆唇，接近 /r/ 时可略向前。",
    airflowInstructions: "声带持续震动，气流不摩擦，不要额外加一个硬 /r/ 擦音。",
    coachTips: "for 不要变成 fall。结尾需要明显的 r-colored 舌头后收。",
    guideWord: "for",
    minimalPairs: [
      { word1: "for", word2: "fall", ipa1: "fɔɹ", ipa2: "fɔl", note: "Retract into /r/ for 'for'" },
      { word1: "more", word2: "maw", ipa1: "mɔɹ", ipa2: "mɔ", note: "Do not drop the r-coloring in 'more'" },
    ],
    practiceWords: ["for", "more", "four", "before", "morning", "story", "important", "short"],
  },
  "ɑɹ": {
    symbol: "ɑɹ",
    ipaSymbol: "ɑɹ",
    name: "Open R-colored Vowel (开口 R 色彩元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "wide",
    velum: "closed",
    descriptionCn: "开口元音接 R 色彩。先张口发低后 /ɑ/，再舌头后收形成 /r/ 共鸣。像 car, hard。",
    descriptionEn: "An open vowel followed by r-coloring. Start with a low back /ɑ/, then retract the tongue into /r/ resonance, as in 'car' and 'hard'.",
    tongueInstructions: "先舌体低后，再向后收；舌尖保持悬空。",
    lipInstructions: "开口较大，进入 /r/ 时可略微收圆。",
    airflowInstructions: "声带持续震动，元音和 r 色彩连成一个流畅整体。",
    coachTips: "car 不要只发成 cah。结尾要有舌头后收的 r 色彩。",
    guideWord: "car",
    minimalPairs: [
      { word1: "car", word2: "caw", ipa1: "kɑɹ", ipa2: "kɔ", note: "Add r-coloring at the end of 'car'" },
      { word1: "hard", word2: "hod", ipa1: "hɑɹd", ipa2: "hɑd", note: "Keep the r-colored center in 'hard'" },
    ],
    practiceWords: ["car", "far", "hard", "park", "start", "large", "heart", "are"],
  },
  "ɛɹ": {
    symbol: "ɛɹ",
    ipaSymbol: "ɛɹ",
    name: "Front R-colored Vowel (前元音加 R 色彩)",
    type: "vowel",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "medium",
    velum: "closed",
    descriptionCn: "前中元音接 R 色彩。先是 /ɛ/ 附近的前元音，再迅速转入 /r/ 的舌头后收。像 care, there。",
    descriptionEn: "A front vowel followed by r-coloring. Start near /ɛ/, then quickly move into English /r/ resonance, as in 'care' and 'there'.",
    tongueInstructions: "舌前部先在中位，随后舌体后收，舌尖悬空。",
    lipInstructions: "嘴唇自然开口，进入 r 色彩时可略微收圆。",
    airflowInstructions: "声带持续震动，避免在元音和 /r/ 之间断开。",
    coachTips: "there 不要只剩 they。结尾的 /r/ 色彩要保留。",
    guideWord: "care",
    minimalPairs: [
      { word1: "care", word2: "kay", ipa1: "kɛɹ", ipa2: "keɪ", note: "Keep r-coloring in 'care'" },
      { word1: "there", word2: "they", ipa1: "ðɛɹ", ipa2: "ðeɪ", note: "Do not replace /ɛɹ/ with /eɪ/" },
    ],
    practiceWords: ["care", "there", "where", "air", "pair", "share", "parent", "various"],
  },
  "ɪɹ": {
    symbol: "ɪɹ",
    ipaSymbol: "ɪɹ",
    name: "Near R-colored Vowel (近音 R 色彩元音)",
    type: "vowel",
    voiced: true,
    tonguePosition: "neutral",
    mouthOpening: "narrow",
    velum: "closed",
    descriptionCn: "高前短元音接 R 色彩。先像 /ɪ/ 一样短而高前，再舌头后收形成 /r/。像 near, here。",
    descriptionEn: "A short high front vowel followed by r-coloring. Start near /ɪ/, then retract into English /r/ resonance, as in 'near' and 'here'.",
    tongueInstructions: "舌前部先抬起，随后舌体向后收，舌尖悬空。",
    lipInstructions: "嘴唇轻微展开，进入 /r/ 时略收。",
    airflowInstructions: "声带持续震动，两个部分要顺滑连接。",
    coachTips: "near 不要读成 knee。结尾必须收进 r-colored 共鸣。",
    guideWord: "near",
    minimalPairs: [
      { word1: "near", word2: "knee", ipa1: "nɪɹ", ipa2: "ni", note: "Add r-coloring at the end of 'near'" },
      { word1: "here", word2: "he", ipa1: "hɪɹ", ipa2: "hi", note: "Do not drop the r-colored ending" },
    ],
    practiceWords: ["near", "here", "year", "clear", "dear", "period", "serious", "engineer"],
  },
  "aʊɹ": {
    symbol: "aʊɹ",
    ipaSymbol: "aʊɹ",
    name: "Diphthong + R-colored Ending (双元音加 R 色彩)",
    type: "diphthong",
    voiced: true,
    tonguePosition: "diphthong-aw",
    mouthOpening: "wide",
    velum: "closed",
    descriptionCn: "先发 /aʊ/ 的开口到圆唇滑动，再接入英语 /r/ 的舌头后收。像 power, hour。",
    descriptionEn: "Start with the /aʊ/ diphthong, gliding from open to rounded, then move into English /r/ resonance, as in 'power' and 'hour'.",
    tongueInstructions: "舌头从低位滑向后高位置，最后向后收形成 /r/。",
    lipInstructions: "先开口，再收圆，进入 /r/ 时保持轻微前伸。",
    airflowInstructions: "声带持续震动，三段动作要连成一个音节。",
    coachTips: "power 不要断成 pow-er 两个硬块；滑动后自然收进 r 色彩。",
    guideWord: "power",
    minimalPairs: [
      { word1: "power", word2: "pow", ipa1: "paʊɹ", ipa2: "paʊ", note: "Keep the r-colored ending in 'power'" },
      { word1: "hour", word2: "how", ipa1: "aʊɹ", ipa2: "haʊ", note: "R-color the end of 'hour'" },
    ],
    practiceWords: ["power", "hour", "our", "flower", "shower", "tower", "around", "ours"],
  },
};

Object.assign(PHONEME_GUIDES, ADDITIONAL_PHONEME_GUIDES);

PHONEME_GUIDES["ɹ"] = PHONEME_GUIDES.r;

export function getFallbackGuide(symbol: string): PhonemeGuide {
  const cleanSymbol = symbol.trim().toLowerCase();
  
  // Smarter categorizer traits
  const isNasal = ["m", "n", "ng", "ŋ"].some(char => cleanSymbol.includes(char));
  const isFricative = ["s", "z", "f", "v", "sh", "ʃ", "zh", "ʒ", "h", "th", "θ", "dh", "ð"].some(char => cleanSymbol === char);
  const isPlosive = ["p", "b", "t", "d", "k", "g"].some(char => cleanSymbol === char);
  
  // Voiced state detection
  const isVoiceless = ["p", "t", "k", "f", "s", "sh", "ch", "th", "θ", "tʃ", "ʃ"].some(char => cleanSymbol === char);
  const voiced = !isVoiceless;

  let type: PhonemeGuide["type"] = "vowel";
  let tonguePosition: PhonemeGuide["tonguePosition"] = "neutral";
  let mouthOpening: PhonemeGuide["mouthOpening"] = "medium";
  let velum: PhonemeGuide["velum"] = "closed";

  if (isNasal) {
    type = "nasal";
    velum = "open";
    if (cleanSymbol === "m") {
      tonguePosition = "neutral";
      mouthOpening = "closed";
    } else if (cleanSymbol === "n") {
      tonguePosition = "alveolar";
      mouthOpening = "narrow";
    } else {
      tonguePosition = "velar";
      mouthOpening = "narrow";
    }
  } else if (isFricative) {
    type = "fricative";
    mouthOpening = "narrow";
    if (["s", "z"].includes(cleanSymbol)) {
      tonguePosition = "alveolar";
    } else if (["th", "θ", "dh", "ð"].includes(cleanSymbol)) {
      tonguePosition = "dental";
    } else {
      tonguePosition = "neutral";
    }
  } else if (isPlosive) {
    type = "plosive";
    if (["p", "b"].includes(cleanSymbol)) {
      tonguePosition = "neutral";
      mouthOpening = "closed";
    } else if (["t", "d"].includes(cleanSymbol)) {
      tonguePosition = "alveolar";
      mouthOpening = "narrow";
    } else {
      tonguePosition = "velar";
      mouthOpening = "narrow";
    }
  } else {
    // Check if it's a known diphthong alias
    const isDiphthong = ["ey", "eɪ", "ay", "aɪ", "oy", "ɔɪ", "aw", "aʊ", "ow", "əʊ", "oʊ", "ow", "ɪə", "ihr", "eə", "ehr", "ʊə", "uhr"].includes(cleanSymbol);
    if (isDiphthong) {
      type = "diphthong";
      tonguePosition = cleanSymbol.includes("ey") || cleanSymbol.includes("eɪ") ? "diphthong-ey" : "diphthong-ay";
    }
  }

  const cleanName = type === "nasal" ? "Nasal Consonant (鼻音)"
                  : type === "fricative" ? "Fricative Consonant (擦音)"
                  : type === "plosive" ? "Plosive Consonant (爆破音)"
                  : type === "diphthong" ? "Diphthong Vowel (双元音)"
                  : "Vowel (单元音)";

  return {
    symbol,
    ipaSymbol: symbol,
    name: `${cleanName} /${symbol}/`,
    type,
    voiced,
    tonguePosition,
    mouthOpening,
    velum,
    descriptionCn: `音素 /${symbol}/ 详细练习指南正在收录中。你可以直接收听标准发音，并对照底部的词汇或在主界面进行反复对比练习。`,
    descriptionEn: `Pronunciation details for sound /${symbol}/ are being compiled. You can listen to standard audio models directly and practice along in the workspace.`,
    tongueInstructions: tonguePosition === "alveolar" ? "舌尖轻轻抵住上门牙后的齿龈阻挡或收窄气流。"
                      : tonguePosition === "velar" ? "舌后部（舌根）抬起，贴住上腭后部的软腭封闭通道。"
                      : tonguePosition === "dental" ? "舌尖轻轻伸出放置于上下齿之间（轻咬舌尖）。"
                      : "舌头保持自然状态，或根据音节连读平滑调整。",
    lipInstructions: mouthOpening === "closed" ? "双唇完全闭合贴拢，封阻腔体。"
                   : mouthOpening === "narrow" ? "双唇略微展开呈微笑扁平状，露出上下排牙齿。"
                   : "双唇自然拉开呈放松的椭圆状。",
    airflowInstructions: velum === "open" ? "软腭自然下垂，气流被迫从口腔后部改道从鼻腔流出。"
                       : type === "plosive" ? "气流在口腔闭合处蓄积，随后突发释出产生爆破声。"
                       : "气流从口腔均匀呼出，声带随清浊音分类相应震动或静止。",
    coachTips: `在练习含有 /${symbol}/ 的词汇时，点击发音键反复模仿标准音频，观察其在词中与周围字母的连读衔接！`,
    guideWord: symbol,
    minimalPairs: [],
    practiceWords: [symbol],
  };
}
